### ISSUE TITLE
xrayr error 

### ISSUE THREAD

**Issue by quocn9043** [XrayR-project/XrayR#582]
how to fix this error : https://appdevtools.com/pastebin/cHOYYI

**Comment by thh1451** [comment]
Thank you for reaching out with the logs. After a examination, it appears that the issue is not related to XrayR. The problem seems to be potentially caused by the your API. We recommend investigating the API configurations to identify and resolve the underlying issue.

If you have any further questions or need assistance in troubleshooting, feel free to let us know.
