### ISSUE TITLE
我想制作新的面板程序，但是缺乏接口文档

### ISSUE THREAD

**Issue by singleDog1123** [XrayR-project/XrayR#679]
能否出一份现有api的接口文档，或者做一套通用版本的api？

**Comment by theresaarcher** [comment]
Thank you for reaching out.

You might find it helpful to refer to the APIs provided by newV2board or v2raysocks for your implementation. Please note that the node configuration files issued by v2raysocks are standard Xray configuration files. Additionally, v2raysocks uses query strings instead of multiple paths for configuration.
