### ISSUE TITLE
XrayR 0.9.4 在关闭Custom_config 时path不是我设定的

### ISSUE THREAD

**Issue by OPPO9008** [XrayR-project/XrayR#680]
```
root@ip-172-26-2-249:~# curl -I 127.0.0.1/
HTTP/1.1 404 Not Found
Date: Sat, 10 Aug 2024 14:26:32 GMT
```

在版本 0.9.2工作正常

**Comment by theresaarcher** [comment]
Thank you for reaching out and reporting this issue. To better assist you and provide a more accurate solution, could you please provide the following details:

Detailed Steps to Reproduce: Can you describe the exact steps you followed before encountering the issue? This will help us replicate the problem on our end.

Error Messages or Logs: If there are any error messages, logs, or screenshots related to the issue, please share them. They can provide valuable insights into the root cause of the problem.

Expected vs. Actual Behavior: What was the expected outcome, and how does it differ from what actually occurred?

Any Additional Information: If there is anything else you think might be relevant to the issue, please include it.

**Comment by OPPO9008** [comment]
安装版本大于 0.9.2 的 xrayr
sspanel 端 ip;80;0;ws;;path=/?ed=2450|host=gd.189.cn|server=ip|outside_port=80

xrayr 关闭Custom_config

**Comment by theresaarcher** [comment]
Please contact your panel developer
